# Generated by Django 3.1.3 on 2022-05-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_firstbasicculture_firstgaesinbasicculture_firstnaturalscience_firstsemesterswmajor_ocu_secondbasiccu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstbasicculture',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='firstbasicculture',
            name='학점부여',
        ),
        migrations.RemoveField(
            model_name='firstgaesinbasicculture',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='firstgaesinbasicculture',
            name='학점부여',
        ),
        migrations.RemoveField(
            model_name='firstnaturalscience',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='firstnaturalscience',
            name='학점부여',
        ),
        migrations.RemoveField(
            model_name='firstsemestermajor',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='firstsemestermajor',
            name='학점부여',
        ),
        migrations.RemoveField(
            model_name='firstsemesterswmajor',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='firstsemesterswmajor',
            name='학점부여',
        ),
        migrations.RemoveField(
            model_name='ocu',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='ocu',
            name='학점부여',
        ),
        migrations.RemoveField(
            model_name='secondbasicculture',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='secondbasicculture',
            name='학점부여',
        ),
        migrations.RemoveField(
            model_name='secondgaesinbasicculture',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='secondgaesinbasicculture',
            name='학점부여',
        ),
        migrations.RemoveField(
            model_name='secondnaturalscience',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='secondnaturalscience',
            name='학점부여',
        ),
        migrations.RemoveField(
            model_name='secondsemestermajor',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='secondsemestermajor',
            name='학점부여',
        ),
        migrations.RemoveField(
            model_name='secondsemesterswmajor',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='secondsemesterswmajor',
            name='학점부여',
        ),
    ]
