# Generated by Django 3.1.3 on 2022-05-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20220505_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploaded_file', models.FileField(upload_to='result/')),
                ('date_time_of_upload', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
