# Generated by Django 3.1.3 on 2022-05-05 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsemestermajor',
            name='과목구분',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='과목구분'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstsemestermajor',
            name='과목명',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='과목명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstsemestermajor',
            name='과목코드',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='과목코드'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstsemestermajor',
            name='학년',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='학년'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstsemestermajor',
            name='학점',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='학점'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstsemestermajor',
            name='학점부여',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='학점부여'),
            preserve_default=False,
        ),
    ]
