# Generated by Django 3.1.3 on 2022-05-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20220505_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstBasicCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('학년', models.CharField(max_length=150, verbose_name='학년')),
                ('과목구분', models.CharField(max_length=150, verbose_name='과목구분')),
                ('과목코드', models.CharField(max_length=150, verbose_name='과목코드')),
                ('과목명', models.CharField(max_length=200, verbose_name='과목명')),
                ('학점', models.CharField(max_length=150, verbose_name='학점')),
                ('학점부여', models.CharField(max_length=150, verbose_name='학점부여')),
            ],
        ),
        migrations.CreateModel(
            name='FirstGaesinBasicCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('학년', models.CharField(max_length=150, verbose_name='학년')),
                ('과목구분', models.CharField(max_length=150, verbose_name='과목구분')),
                ('과목코드', models.CharField(max_length=150, verbose_name='과목코드')),
                ('과목명', models.CharField(max_length=200, verbose_name='과목명')),
                ('학점', models.CharField(max_length=150, verbose_name='학점')),
                ('학점부여', models.CharField(max_length=150, verbose_name='학점부여')),
            ],
        ),
        migrations.CreateModel(
            name='FirstNaturalScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('학년', models.CharField(max_length=150, verbose_name='학년')),
                ('과목구분', models.CharField(max_length=150, verbose_name='과목구분')),
                ('과목코드', models.CharField(max_length=150, verbose_name='과목코드')),
                ('과목명', models.CharField(max_length=200, verbose_name='과목명')),
                ('학점', models.CharField(max_length=150, verbose_name='학점')),
                ('학점부여', models.CharField(max_length=150, verbose_name='학점부여')),
            ],
        ),
        migrations.CreateModel(
            name='FirstSemesterSWMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('학년', models.CharField(max_length=150, verbose_name='학년')),
                ('과목구분', models.CharField(max_length=150, verbose_name='과목구분')),
                ('과목코드', models.CharField(max_length=150, verbose_name='과목코드')),
                ('과목명', models.CharField(max_length=200, verbose_name='과목명')),
                ('학점', models.CharField(max_length=150, verbose_name='학점')),
                ('학점부여', models.CharField(max_length=150, verbose_name='학점부여')),
            ],
        ),
        migrations.CreateModel(
            name='Ocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('학년', models.CharField(max_length=150, verbose_name='학년')),
                ('과목구분', models.CharField(max_length=150, verbose_name='과목구분')),
                ('과목코드', models.CharField(max_length=150, verbose_name='과목코드')),
                ('과목명', models.CharField(max_length=200, verbose_name='과목명')),
                ('학점', models.CharField(max_length=150, verbose_name='학점')),
                ('학점부여', models.CharField(max_length=150, verbose_name='학점부여')),
            ],
        ),
        migrations.CreateModel(
            name='SecondBasicCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('학년', models.CharField(max_length=150, verbose_name='학년')),
                ('과목구분', models.CharField(max_length=150, verbose_name='과목구분')),
                ('과목코드', models.CharField(max_length=150, verbose_name='과목코드')),
                ('과목명', models.CharField(max_length=200, verbose_name='과목명')),
                ('학점', models.CharField(max_length=150, verbose_name='학점')),
                ('학점부여', models.CharField(max_length=150, verbose_name='학점부여')),
            ],
        ),
        migrations.CreateModel(
            name='SecondGaesinBasicCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('학년', models.CharField(max_length=150, verbose_name='학년')),
                ('과목구분', models.CharField(max_length=150, verbose_name='과목구분')),
                ('과목코드', models.CharField(max_length=150, verbose_name='과목코드')),
                ('과목명', models.CharField(max_length=200, verbose_name='과목명')),
                ('학점', models.CharField(max_length=150, verbose_name='학점')),
                ('학점부여', models.CharField(max_length=150, verbose_name='학점부여')),
            ],
        ),
        migrations.CreateModel(
            name='SecondNaturalScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('학년', models.CharField(max_length=150, verbose_name='학년')),
                ('과목구분', models.CharField(max_length=150, verbose_name='과목구분')),
                ('과목코드', models.CharField(max_length=150, verbose_name='과목코드')),
                ('과목명', models.CharField(max_length=200, verbose_name='과목명')),
                ('학점', models.CharField(max_length=150, verbose_name='학점')),
                ('학점부여', models.CharField(max_length=150, verbose_name='학점부여')),
            ],
        ),
        migrations.CreateModel(
            name='SecondSemesterMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('학년', models.CharField(max_length=150, verbose_name='학년')),
                ('과목구분', models.CharField(max_length=150, verbose_name='과목구분')),
                ('과목코드', models.CharField(max_length=150, verbose_name='과목코드')),
                ('과목명', models.CharField(max_length=200, verbose_name='과목명')),
                ('학점', models.CharField(max_length=150, verbose_name='학점')),
                ('학점부여', models.CharField(max_length=150, verbose_name='학점부여')),
            ],
        ),
        migrations.CreateModel(
            name='SecondSemesterSWMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('학년', models.CharField(max_length=150, verbose_name='학년')),
                ('과목구분', models.CharField(max_length=150, verbose_name='과목구분')),
                ('과목코드', models.CharField(max_length=150, verbose_name='과목코드')),
                ('과목명', models.CharField(max_length=200, verbose_name='과목명')),
                ('학점', models.CharField(max_length=150, verbose_name='학점')),
                ('학점부여', models.CharField(max_length=150, verbose_name='학점부여')),
            ],
        ),
    ]
