# Generated by Django 3.1.3 on 2022-05-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_ai_application_embedded_game_network'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
